import { Document } from "@/types/documents";
export const documents: Document[] = [
  // Measures
  {
    id: "1",
    title: "Annual Safety Measures Report",
    description: "Comprehensive safety protocols and implementations",
    category: "measures",
    year: 2024,
    date: "2024-11-15",
    fileType: "pdf",
  },
  {
    id: "2",
    title: "Environmental Protection Guidelines",
    description: "Updated environmental standards",
    category: "measures",
    year: 2024,
    date: "2024-08-22",
    fileType: "pdf",
  },
  {
    id: "3",
    title: "Quality Control Standards",
    description: "New quality assurance protocols",
    category: "measures",
    year: 2024,
    date: "2024-03-10",
    fileType: "doc",
  },
  {
    id: "4",
    title: "Risk Assessment Framework",
    description: "Risk management procedures",
    category: "measures",
    year: 2023,
    date: "2023-12-05",
    fileType: "pdf",
  },
  {
    id: "5",
    title: "Compliance Regulations Update",
    description: "Regulatory compliance updates",
    category: "measures",
    year: 2023,
    date: "2023-06-18",
    fileType: "pdf",
  },
  {
    id: "6",
    title: "Safety Protocol Revision",
    description: "Updated safety guidelines",
    category: "measures",
    year: 2022,
    date: "2022-09-30",
    fileType: "doc",
  },

  // Informs
  {
    id: "7",
    title: "Q4 Performance Report",
    description: "Quarterly performance analysis",
    category: "informs",
    year: 2024,
    date: "2024-12-01",
    fileType: "pdf",
  },
  {
    id: "8",
    title: "Market Analysis Summary",
    description: "Market trends and insights",
    category: "informs",
    year: 2024,
    date: "2024-09-15",
    fileType: "xls",
  },
  {
    id: "9",
    title: "Stakeholder Communication Brief",
    description: "Key stakeholder updates",
    category: "informs",
    year: 2024,
    date: "2024-05-20",
    fileType: "pdf",
  },
  {
    id: "10",
    title: "Annual Review 2023",
    description: "Year-end comprehensive review",
    category: "informs",
    year: 2023,
    date: "2023-12-28",
    fileType: "pdf",
  },
  {
    id: "11",
    title: "Industry Benchmark Report",
    description: "Competitive analysis",
    category: "informs",
    year: 2023,
    date: "2023-07-12",
    fileType: "pdf",
  },
  {
    id: "12",
    title: "Customer Feedback Analysis",
    description: "Client satisfaction metrics",
    category: "informs",
    year: 2022,
    date: "2022-11-08",
    fileType: "xls",
  },

  // Advances
  {
    id: "13",
    title: "Technology Roadmap 2025",
    description: "Future technology initiatives",
    category: "advances",
    year: 2024,
    date: "2024-10-25",
    fileType: "pdf",
  },
  {
    id: "14",
    title: "Innovation Pipeline Update",
    description: "New product developments",
    category: "advances",
    year: 2024,
    date: "2024-07-08",
    fileType: "pdf",
  },
  {
    id: "15",
    title: "R&D Progress Report",
    description: "Research and development updates",
    category: "advances",
    year: 2024,
    date: "2024-02-14",
    fileType: "doc",
  },
  {
    id: "16",
    title: "Digital Transformation Plan",
    description: "Digitalization strategy",
    category: "advances",
    year: 2023,
    date: "2023-11-20",
    fileType: "pdf",
  },
  {
    id: "17",
    title: "Process Improvement Initiatives",
    description: "Operational enhancements",
    category: "advances",
    year: 2023,
    date: "2023-04-05",
    fileType: "pdf",
  },
  {
    id: "18",
    title: "Sustainability Roadmap",
    description: "Green initiatives planning",
    category: "advances",
    year: 2022,
    date: "2022-08-17",
    fileType: "pdf",
  },
];
